# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Client install
      working-directory: ./Scoprimi
      run: npm ci

    - name: Server install
      working-directory: ./Server
      run: npm ci
    
    - name: Client install
      working-directory: ./Scoprimi
      run: npm run build --if-present

    - name: Server install
      working-directory: ./Server
      run: npm run build --if-present

    - name: Client install
      working-directory: ./Scoprimi
      run: npx eslint

    - name: Server install
      working-directory: ./Server
      run: npx eslint
      
      
