name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [ubuntu-latest, windows-latest]

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Client dependencies
      working-directory: ./Scoprimi
      run: npm ci

    - name: Install Server dependencies
      working-directory: ./Server
      run: npm ci

    - name: Build Client
      working-directory: ./Scoprimi
      run: npm run build --if-present

    - name: Build Server
      working-directory: ./Server
      run: npm run build --if-present

    - name: Lint Client
      working-directory: ./Scoprimi
      run: npx eslint .

    - name: Lint Server
      working-directory: ./Server
      run: npx eslint .
